(defpackage "DATA-FLOW.FEATURES"
  (:use "COMMON-LISP")
  (:export "FEATURE-UNAVAILABLE-ERROR")

  (:export "THREADS"
           "THREADS-UNAVAILABLE-ERROR")

  (:export "COMPARE-AND-SET"
           "COMPARE-AND-SET-UNAVAILABLE-ERROR"))
